app:
  env: dev # 环境 dev/prod
  database: mysql # 数据库选择

postgresql:
  host: localhost
  user: postgres
  password: 123456
  dbname: postgres
  port: 5432
  timezone: Asia/Shanghai

mysql:
  host: localhost
  user: root
  password: 123456
  dbname: example
  port: 3306
  timezone: Asia/Shanghai

redis:
  address: localhost:6379
  password: 123456
  db: 0
  pool-size: 100
  min-idle-conns: 10

rabbitmq:
  user: guest
  password: guest
  host: localhost
  port: 5672

kafka:
  host: localhost
  port: 9092

logs:
  level: info # 日志等级
  root_dir: ./logs # 日志根目录
  filename: app.log # 日志文件名称
  db_filename: db.log # 慢日志
  format: # 写入格式 可选json
  show_line: true # 是否显示调用行
  max_backups: 3 # 旧文件的最大个数
  max_size: 2 # 日志文件最大大小（MB）
  max_age: 28 # 旧文件的最大保留天数
  compress: false # 是否压缩

distlock:
  type: redsync
  retry_count: 10
  retry_delay: 200