database:
  host: localhost
  user: postgres
  password: 123456
  dbname: postgres
  port: 5432
  timezone: Asia/Shanghai

redis:
  address: localhost:6379
  password: 123456
  db: 0
  pool-size: 100
  min-idle-conns: 10

rabbitmq:
  user: guest
  password: guest
  host: localhost
  port: 5672
